"""Provision a funded Stellar testnet account for the paywall treasury.

Generates a keypair, funds it with Friendbot (free, no signup), and writes the
keys into ``backend/.env``. Existing values are preserved unless ``--force``
is passed.

    python scripts/setup_stellar.py
    python scripts/setup_stellar.py --force
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import httpx

BACKEND_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_ROOT))

ENV_PATH = BACKEND_ROOT / ".env"
FRIENDBOT = "https://friendbot.stellar.org"
HORIZON = "https://horizon-testnet.stellar.org"


def read_env() -> dict[str, str]:
    if not ENV_PATH.exists():
        return {}
    values: dict[str, str] = {}
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.split("#")[0].strip()
    return values


def write_env(updates: dict[str, str]) -> None:
    lines = (
        ENV_PATH.read_text(encoding="utf-8").splitlines()
        if ENV_PATH.exists()
        else []
    )
    remaining = dict(updates)

    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key = stripped.split("=", 1)[0].strip()
        if key in remaining:
            lines[index] = f"{key}={remaining.pop(key)}"

    if remaining:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append("# ── Stellar (generated by scripts/setup_stellar.py) ──")
        lines.extend(f"{key}={value}" for key, value in remaining.items())

    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def fund(public_key: str) -> float:
    with httpx.Client(timeout=45.0) as client:
        response = client.get(FRIENDBOT, params={"addr": public_key})
        if response.status_code >= 400 and "already funded" not in response.text.lower():
            raise SystemExit(
                f"Friendbot rejected the request ({response.status_code}): "
                f"{response.text[:300]}"
            )
        account = client.get(f"{HORIZON}/accounts/{public_key}")
        account.raise_for_status()
        balances = account.json().get("balances", [])
    native = next((b for b in balances if b.get("asset_type") == "native"), None)
    return float(native["balance"]) if native else 0.0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force", action="store_true", help="Replace an existing keypair"
    )
    args = parser.parse_args()

    from stellar_sdk import Keypair

    env = read_env()
    existing_public = env.get("STELLAR_PUBLIC_KEY", "").strip()

    if existing_public and not args.force:
        print(f"Treasury account already configured: {existing_public}")
        try:
            balance = fund(existing_public)
            print(f"Balance: {balance:.4f} XLM (topped up via Friendbot)")
        except Exception as exc:
            print(f"Could not refresh balance: {exc}")
        print("Re-run with --force to generate a new keypair.")
        return 0

    keypair = Keypair.random()
    print(f"Generated testnet keypair: {keypair.public_key}")
    print("Funding via Friendbot…")
    balance = fund(keypair.public_key)

    write_env(
        {
            "STELLAR_NETWORK": "testnet",
            "STELLAR_HORIZON_URL": HORIZON,
            "STELLAR_PUBLIC_KEY": keypair.public_key,
            "STELLAR_SECRET_KEY": keypair.secret,
        }
    )

    print(f"Funded with {balance:.4f} XLM")
    print(f"Keys written to {ENV_PATH}")
    print(f"Explorer: https://stellar.expert/explorer/testnet/account/{keypair.public_key}")
    print("\nRestart the API server to pick up the new configuration.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
